# Generated by Django 4.2.7 on 2024-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_student_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default='1', max_length=1, verbose_name='Current Semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(choices=[('7', '2022/2023'), ('6', '2021/2022'), ('5', '2019/2020'), ('4', '2018/2019'), ('3', '2017/2018'), ('2', '2016/2017'), ('1', '2015/2016')], default='7', max_length=3, verbose_name='Current Academic Session'),
        ),
    ]
