# Generated by Django 4.2.7 on 2024-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_student_semester_alter_student_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1', '100 Level'), ('2', '200 Level'), ('3', '300 Level'), ('4', '400 Level'), ('5', '500 Level'), ('6', 'Spill One'), ('7', 'Spill Two')], max_length=1, verbose_name='Current Level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(choices=[('8', '2023/2024'), ('7', '2022/2023'), ('6', '2021/2022'), ('5', '2019/2020'), ('4', '2018/2019'), ('3', '2017/2018'), ('2', '2016/2017'), ('1', '2015/2016')], default='7', max_length=3, verbose_name='Current Academic Session'),
        ),
    ]
