# Generated by Django 4.2.7 on 2024-01-13 21:23

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Course Title')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='Course Code')),
                ('units', models.IntegerField(default=4, verbose_name='Units')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Course Description')),
                ('designation', models.CharField(choices=[('CL', 'Compulsory Law Course'), ('CU', 'Compulsory University Course (GST/ENT)'), ('OL', 'Optional Law Course'), ('CN', 'Compulsory Non Law Course'), ('OT', 'Others; Non Law/University Course')], max_length=2, verbose_name='Course Type')),
                ('outline', models.TextField(verbose_name='Course Outline')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('14', '2029/2030'), ('13', '2028/2029'), ('12', '2027,2028'), ('11', '2026/2027'), ('10', '2025/2026'), ('9', '2024/2025'), ('8', '2023/2024'), ('7', '2022/2023'), ('6', '2021/2022'), ('5', '2019/2020'), ('4', '2018/2019'), ('3', '2017/2018'), ('2', '2016/2017'), ('1', '2015/2016')], max_length=3, verbose_name='Academic Session')),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=1, verbose_name='Semester')),
                ('TCP', models.IntegerField(blank=True, null=True, verbose_name='Total Credit Passed')),
                ('TLU', models.IntegerField(blank=True, null=True, verbose_name='Total Load Unit')),
                ('GPA', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Grade Point Average')),
                ('max_unit', models.IntegerField(default=28, verbose_name='Maximum Units')),
                ('min_unit', models.IntegerField(default=15, verbose_name='Minimum Units')),
                ('gst', models.IntegerField(default=0, verbose_name='Units for GST/ENT')),
                ('compulsory', models.IntegerField(default=0, verbose_name='Units for Compulsory Law Courses')),
                ('compulsory_other', models.IntegerField(default=0, verbose_name='Units for Compulsory Non-Law Courses')),
                ('optional_law', models.IntegerField(default=0, verbose_name='Units for Elective Law Courses')),
                ('optional_others', models.IntegerField(default=0, verbose_name='Units for Elective Non-Law Courses')),
                ('main', models.IntegerField(default=0, verbose_name='Units for Original Semester Courses')),
                ('outstanding', models.IntegerField(default=0, verbose_name='Units for Outstanding Courses')),
                ('total', models.IntegerField(default=0, verbose_name='Total Units')),
                ('is_registered', models.BooleanField(default=False)),
                ('current_semester', models.BooleanField(default=False)),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Courses Registration',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('exam', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=12, null=True)),
                ('course_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Course_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=courses.models.upload_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'gif', 'doc', 'docx', 'csv', 'xlsx']), courses.models.FileSizeValidator], verbose_name='Course Materials')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Uploads for Courses',
                'verbose_name_plural': 'Uploads for Courses',
            },
        ),
    ]
