# Generated by Django 4.2.7 on 2024-01-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_level_course_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('7', '2022/2023'), ('6', '2021/2022'), ('5', '2019/2020'), ('4', '2018/2019'), ('3', '2017/2018'), ('2', '2016/2017'), ('1', '2015/2016')], max_length=3, verbose_name='Academic Session')),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=1, verbose_name='Semester')),
                ('current_semester', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='current_semester',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='session',
        ),
        migrations.AlterField(
            model_name='course_registration',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
        ),
    ]
