# Generated by Django 4.2.7 on 2024-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_semester_remove_course_registration_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='deans_list',
            field=models.BooleanField(default=False, verbose_name="Dean's List"),
        ),
        migrations.AddField(
            model_name='course_registration',
            name='student_status',
            field=models.CharField(blank=True, choices=[('GS', 'Good Standing'), ('PR', 'Probation'), ('LA', 'Leave of Absence')], max_length=20, null=True),
        ),
    ]
