# Generated by Django 4.2.7 on 2024-01-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_student_session'),
        ('courses', '0006_alter_semester_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_registration',
            name='GPA',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='TCP',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='TLU',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='compulsory',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='compulsory_other',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='deans_list',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='main',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='max_unit',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='min_unit',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='optional_law',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='optional_others',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='student_status',
        ),
        migrations.RemoveField(
            model_name='course_registration',
            name='total',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '100 Level'), ('2', '200 Level'), ('3', '300 Level'), ('4', '400 Level'), ('5', '500 Level')], max_length=1, null=True, verbose_name='Current Level'),
        ),
        migrations.AlterField(
            model_name='course_uploads',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course'),
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.CharField(blank=True, choices=[('GS', 'Good Standing'), ('PR', 'Probation'), ('LA', 'Leave of Absence')], max_length=20, null=True)),
                ('TCP', models.IntegerField(blank=True, null=True, verbose_name='Total Credit Passed')),
                ('TLU', models.IntegerField(blank=True, null=True, verbose_name='Total Load Unit')),
                ('GPA', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Grade Point Average')),
                ('max_unit', models.IntegerField(default=28, verbose_name='Maximum Units')),
                ('min_unit', models.IntegerField(default=15, verbose_name='Minimum Units')),
                ('gst', models.IntegerField(default=0, verbose_name='Units for GST/ENT')),
                ('compulsory', models.IntegerField(default=0, verbose_name='Units for Compulsory Law Courses')),
                ('compulsory_other', models.IntegerField(default=0, verbose_name='Units for Compulsory Non-Law Courses')),
                ('optional_law', models.IntegerField(default=0, verbose_name='Units for Elective Law Courses')),
                ('optional_others', models.IntegerField(default=0, verbose_name='Units for Elective Non-Law Courses')),
                ('main', models.IntegerField(default=0, verbose_name='Units for Original Semester Courses')),
                ('outstanding', models.IntegerField(default=0, verbose_name='Units for Outstanding Courses')),
                ('total', models.IntegerField(default=0, verbose_name='Total Units')),
                ('is_registered', models.BooleanField(default=False)),
                ('deans_list', models.BooleanField(default=False, verbose_name="Dean's List")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.student')),
            ],
        ),
    ]
