# Generated by Django 4.2.7 on 2024-01-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_registration_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.semester'),
        ),
    ]
