# Generated by Django 4.2.7 on 2024-01-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_brief_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.semester'),
        ),
    ]
