# Generated by Django 4.2.7 on 2024-01-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_brief_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='compulsory',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='compulsory_other',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='main',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='max_unit',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='min_unit',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='optional_law',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='optional_others',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='total',
        ),
    ]
