# Generated by Django 4.2.7 on 2024-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_brief_compulsory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
